# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_monitorednfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='id_report',
            field=models.IntegerField(default=0, verbose_name='Id denuncia'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='report',
            name='cnpj',
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('id_report', 'user')]),
        ),
    ]
