# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20170819_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('2', 'Deferido'), ('3', 'Indeferido'), ('1', 'Em processamento')], default='1', max_length=1, verbose_name='Status denuncia'),
        ),
    ]
