# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_monitorednfe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorednfe',
            name='status',
            field=models.CharField(choices=[('2', 'Recebido'), ('3', 'Reportado'), ('1', 'Em processamento')], default='1', max_length=1, verbose_name='Status denuncia'),
        ),
    ]
