# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sefaz', '0003_auto_20170819_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='name',
        ),
    ]
