# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sefaz', '0004_auto_20170819_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='teste@teste.com', max_length=255, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=255, verbose_name='Username'),
        ),
    ]
